/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car.rental.system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Raheez
 */
public class viewRentedVehicle extends javax.swing.JFrame {
    String EID;
    
    
    Connection connection = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    Connection connection2 = null;
    PreparedStatement ps2 = null;
    ResultSet rs2 = null;
    
    Connection connection3 = null;
    PreparedStatement ps3 = null;
    ResultSet rs3 = null;
    
    Connection connection4 = null;
    PreparedStatement ps4 = null;
    ResultSet rs4 = null;
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    /**
     * Creates new form viewRentedVehicle
     */
    public viewRentedVehicle() {
        initComponents();
    }
    
        public viewRentedVehicle(String uname) {
        EID = uname;
        initComponents();
        
        Object columns[] = {"Vehicle ID", "Model", "type","Customer name","customer phone","Start date","Due date"};
        defaultTableModel.setColumnIdentifiers(columns);
        jTable1.setModel(defaultTableModel);
        loadData();
    }
        
        public void loadData(){
        connection = Connector.ConnectDb();
        connection2 =Connector.ConnectDb();
        connection3 = Connector.ConnectDb();
        connection4 = Connector.ConnectDb();
        String sql = "select vid from manages where eid='"+EID+"'";
        
        try {
            ps = connection.prepareStatement(sql);
            rs = ps.executeQuery();
            
            
            Object columnData[] = new Object[7];
            while (rs.next()) {
                String sql2="select cid,issuedate,duedate from rentedto where vid='"+rs.getString("vid")+"'";
                
                ps2=connection2.prepareStatement(sql2);
                rs2 = ps2.executeQuery();
                rs2.next();
                
                if(rs2.getString("cid")!=null){
                    
                    String sql3="select name,phone from customers where cid='"+rs2.getString("cid")+"'";
                    ps3=connection3.prepareStatement(sql3);
                    rs3=ps3.executeQuery();
                    
                    rs3.next();
                    
                    String sql4="select model,type from vehicles where vid='"+rs.getString("vid")+"'";
                    ps4=connection4.prepareStatement(sql4);
                    rs4=ps4.executeQuery();
                    
                    rs4.next();
                    
                    
                    columnData[0] = rs.getString("vid");
                    columnData[1] = rs4.getString("model");
                    columnData[2] = rs4.getString("type");
                    columnData[3] = rs3.getString("name");
                    columnData[4] = rs3.getString("phone");
                    columnData[5] = rs2.getString("issuedate");
                    columnData[6] = rs2.getString("duedate");

                    defaultTableModel.addRow(columnData);
                
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ami R", 1, 36)); // NOI18N
        jLabel2.setText("All Rented Vehicles");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Ami R", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 90, 880, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 1110, 690));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/muscle-car-vintage-retrowave-sunset-neon-digital-art-hd-wallpaper-uhdpaper.com-450@0@f.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        employeeActivity emp = new employeeActivity(EID);
        emp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewRentedVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewRentedVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewRentedVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewRentedVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewRentedVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
